export const actionTypes = {
  FETCH_PLAYERS_BEGIN: "PLAYERS/FETCH_PLAYERS_BEGIN",
  FETCH_PLAYERS_SUCCESS: "PLAYERS/FETCH_PLAYERS_SUCCESS",

  FETCH_ALL_PLAYERS: "FETCH_ALL_PLAYERS",
  FETCH_ACTIVE_PLAYERS: "FETCH_ACTIVE_PLAYERS",
  ADD_PLAYER: "ADD_PLAYER",
  REMOVE_PLAYER: "REMOVE_PLAYER",
  TOGGLE_ACTIVE: "TOGGLE_ACTIVE",
  TOGGLE_INACTIVE: "TOGGLE_INACTIVE",
};
